name: CaptureTheDisc
version: '${project.version}'
main: com.simondmc.capturethedisc.CaptureTheDisc
authors: [ SimonDMC ]
description: stuff for dream and techno event ig
website: simondmc.com
api-version: 1.16

commands:
  testcmd:
  pastemap:
  startctd:
  forcestopctd:
  openshop:
  addcoins:
  debugupgrades:
  togglectddev:
  ctdkill:
  pickupdisc:
  togglectdperformance:
  # used in preprocess to override any other shout command while ctd is running
  shout: